version: '3.8'

services:
  ai-service:
    build: ./ai-service
    ports:
      - "8001:8001"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - MODEL_NAME=gpt-4o-mini
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - DEBUG=true
      - MAX_TOKENS=1000
      - TEMPERATURE=0.7
      - TOP_P=0.9
      - CONVERSATION_HISTORY_LIMIT=10
      - CONVERSATION_TTL_HOURS=24
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "19006:19006"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    restart: unless-stopped
    depends_on:
      - ai-service
